apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: boutique-alerts
  namespace: monitoring
  labels:
    release: kube-prom-stack
spec:
  groups:
  - name: boutique.critical
    rules:
    - alert: PodCrashLooping
      expr: rate(kube_pod_container_status_restarts_total{namespace="online-boutique"}[15m]) * 900 > 3
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: "Pod {{ $labels.pod }} crash looping"

    - alert: DeploymentDown
      expr: kube_deployment_status_replicas_available{namespace="online-boutique"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "{{ $labels.deployment }} has 0 replicas"

    - alert: HighMemoryUsage
      expr: container_memory_working_set_bytes{namespace="online-boutique"} / container_spec_memory_limit_bytes{namespace="online-boutique"} > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: "{{ $labels.pod }} memory at {{ $value | humanizePercentage }}"
