apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: redis-secret
  namespace: online-boutique
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets
    kind: ClusterSecretStore
  target:
    name: redis-credentials
  data:
    - secretKey: REDIS_ADDR
      remoteRef:
        key: boutique/prod/redis
        property: REDIS_ADDR
